language: r

warnings_are_errors: false

os:
  - linux
  - osx

r:
  - release

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - _R_CHECK_LATEX_VIGNETTES=FALSE
    - _R_CHECK_WEAVE_VIGNETTES=FALSE

branches:
  only:
  - master
    
sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  # Get PKGVER
  - 'export PKGVER=$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)'
  # CHECK version type by counting dots (flaky)
  - 'export RELEASE=$(grep -o \\. <<< $PKGVER | wc -w)'
  - "echo $RELEASE"
  # Build binary and remove the source archive
  - "R CMD INSTALL --build FLasher_$PKGVER.tar.gz"
  - "rm FLasher_$PKGVER.tar.gz"
  # Look for packages
  - "export RELEASE_PKG_FILE=$(ls FLasher*gz)"
  - "echo $RELEASE_PKG_FILE"

deploy:
  provider: releases
  api_key:
    secure: lB8DTfhYyQ3B6jXeVkXPp9GyT+eN3fBsAlv+23Waex9TxElm/jt7CDOij7MhhimleHR1PMeaQelRu5qHEfDQBoU9kYnxzw7LlqEzN+nWW46yysRaUhtSuTIL7FJYT95wNRHKj/jtW3e2EsSFbbw1+1PvB3k99YDHxfpNOGudRp0=
  file: $RELEASE_PKG_FILE
  skip_cleanup: true
  draft: true
  on:
    repo: flr/FLasher
    # condition: "$RELEASE=2"
    # condition: $RELEASE =~ ^[0-9]+\.[0-9]+\.[0-9]+
