# https://ci.appveyor.com/project/flr/FLPKG
# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

platform: x64

environment:
  global:
    USE_RTOOLS: true 

  matrix:
  - R_VERSION: release
    R_ARCH: x64
    RTOOLS_VERSION: 33

  - R_VERSION: devel
    R_ARCH: x64
    RTOOLS_VERSION: 34

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github flr/FLCore flr/ggplotFL flr/FLFishery

test_script:
  - travis-tool.sh run_tests
  - travis-tool.sh dump_logs
  - 7z a Logs.zip *.Rcheck\*
  - appveyor PushArtifact Logs.zip

on_failure:
  - travis-tool.sh dump_logs
  - 7z a Bits.zip *_*.zip
  - appveyor PushArtifact Bits.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
